### ISSUE TITLE
Brew install fail, directory not empty

### ISSUE THREAD

**Issue by nkrabben** [NYPL/digarch_scripts#18]
brew installs from script sometimes fail with

```sh
directory not empty @ rm_dir ... /private/tmp/....
```

It's not clear what causes this. Fix is to `rm -rf /private/tmp/...` directory and then reinstall. Doesn't feel like a good fix though.

**Comment by bturkus** [comment]
experiencing a slightly diff version of this on Big Sur Mac and needed to run the following to get brew properly installed

```
- Run these two commands in your terminal to add Homebrew to your PATH:
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/benjaminturkus/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
```

**Comment by nkrabben** [comment]
So maybe we need to update the bash profile immediately after install homebrew?

Script could use some functions to make it a bit more modular. This would be a good opportunity to do that.
