### ISSUE TITLE
install script doesn't work for multi-user computers

### ISSUE THREAD

**Issue by cgmcnamara** [NYPL/digarch_scripts#27]
```
Error: Can't create update lock in /usr/local/var/homebrew/locks!
Fix permissions by running:
  sudo chown -R $(whoami) /usr/local/var/homebrew
```

**Comment by nkrabben** [comment]
Homebrew should only be used by the primary user on a Mac.
https://www.codejam.info/2021/11/homebrew-multi-user.html

I haven't thought of what to do for true multi-user setups yet, except everyone logs into the same account, which has its own headaches.

**Comment by nkrabben** [comment]
no longer relevant to this repo
