### ISSUE TITLE
file_number variable doesn't match ASpace import field file_count

### ISSUE THREAD

**Issue by arhonemus** [NYPL/digarch_scripts#37]
#30 [report_ftk_extents](https://github.com/NYPL/digarch_scripts/blob/main/src/digarch_scripts/report_ftk_extents.py) and [report_hdd_extents](https://github.com/NYPL/digarch_scripts/blob/main/src/digarch_scripts/report_hdd_extents.py) file_number should be replaced with file_count to import into ASpace correctly.

**Comment by nkrabben** [comment]
Addressed in #38
