### ISSUE TITLE
Add VS Code Extension installs to install script

### ISSUE THREAD

**Issue by nkrabben** [NYPL/digarch_scripts#4]
Syntax is 

```code --install-extension extension.id```
e.g.
```code --install-extension github.vscode-pull-request-github```
@carolinegil

**Comment by nkrabben** [comment]
Not sure what other extensions to include yet.
I have python, markdown, xml, json, and csv linters

**Comment by nkrabben** [comment]
bmalehorn.shell-syntax
DavidAnson.vscode-markdownlint
DotJoshJohnson.xml
foxundermoon.shell-format
GitHub.vscode-pull-request-github
mechatroner.rainbow-csv
ms-python.python
ms-toolsai.jupyter
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
yzhang.markdown-all-in-one

**Comment by carolinegil** [comment]
Added a PR for these changes

**Comment by nkrabben** [comment]
I'm leaving #5 open for now to collect AR's extensions

@carolinegil you can autolink to PR's by typing their number e.g. #5

**Comment by nkrabben** [comment]
@arhonemus any additional VS Code extensions to add to the default list?

**Comment by arhonemus** [comment]
#spelling
streetsidesoftware.code-spell-checker

**Comment by nkrabben** [comment]
address in #10
