### ISSUE TITLE
Space before colon causes ER number to be unrecognized

### ISSUE THREAD

**Issue by arhonemus** [NYPL/digarch_scripts#49]
When running report_ftk_extents.py the following error occurred and no JSON was created.
Creating report ...
ER is missing a number: ER 004 : Apollo. Review the ERs with the processing archivist
Collection uses ER 0 to ER 903. ER 4 is skipped. Review the ERs with the processing archivist

**Comment by nkrabben** [comment]
I think the response here should be to adjust the bookmark name and rerun the script.
